PUT http://localhost:4004/api/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John mfking Doe again",
  "email": "john.mfdoe12345@example.com",
  "address": "123 Main St, Springfield",
  "dateOfBirth": "1985-06-15"

}